/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6yF6YCUTCLU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Syne } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import React, { useRef } from 'react';
import { useNavigate } from "react-router-dom";
import { motion } from 'framer-motion';
export function Landing() {

  const testimonialsRef = useRef(null);
  const navigate = useNavigate();
  const scrollToTestimonials = (e) => {
    e.preventDefault();
    testimonialsRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    (<div
      className="flex flex-col min-h-[100dvh] bg-gradient-to-b from-[#6a5acd] to-[#8b00ff] text-white">
      <header className="px-4 lg:px-6 h-14 flex items-center justify-between  bg-[#8b00ff]">
        <a href="#" className="flex items-center justify-center" prefetch={false}>
          <ImageIcon className="h-8 w-8 text-white" />
          <span className="text-2xl font-bold">Imagine</span>
        </a>
        <nav className="hidden lg:flex gap-4 sm:gap-6">
          <a
            href=""
            onClick={scrollToTestimonials}
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}>
            Testimonials
          </a>
          
        </nav>
        <Button variant="outline" size="icon" className="lg:hidden">
          <MenuIcon className="h-6 w-6 text-white" />
          <span className="sr-only">Toggle navigation menu</span>
        </Button>
      </header>
      <main className="flex-1  bg-[#8b00ff]">
        <section className="w-full py-12 md:py-24 lg:py-32 relative overflow-hidden">
          <div className="container px-4 md:px-6 text-center">
            <div className="space-y-4 relative z-10">
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tighter">
                Unleash Your Creativity with Imagine
              </h1>
              <p className="max-w-[700px] mx-auto text-lg md:text-xl">
                Imagine is an AI-powered image generation tool that allows you to create stunning visuals with just a
                few words. Bring your ideas to life like never before.
              </p>
              <div className="flex justify-center gap-4">
              <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.95 }}>
                <Button
                  onClick={() => navigate('/generate')}
                  className="inline-flex h-10 items-center justify-center rounded-md bg-white px-6 text-sm font-medium text-[#6a5acd] shadow transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  Try Imagine
                </Button>
                </motion.div>
              
              </div>
            </div>
            <div className="absolute inset-0 -z-10 overflow-hidden">
              <div
                className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-[#6a5acd] to-[#8b00ff] opacity-50 blur-3xl" />
              <div
                className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-[#6a5acd] to-[#8b00ff] opacity-50 blur-3xl animate-pulse" />
              <div
                className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-[#6a5acd] to-[#8b00ff] opacity-50 blur-3xl animate-pulse delay-[1s]" />
              <div
                className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-[#6a5acd] to-[#8b00ff] opacity-50 blur-3xl animate-pulse delay-[2s]" />
            </div>
          </div>
        </section>
        <section id="features" className="w-full py-12 md:py-24 lg:py-32 bg-[#8b00ff]">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter">Unleash Your Creativity</h2>
                <p
                  className="max-w-[900px] text-lg md:text-xl lg:text-base/relaxed xl:text-xl/relaxed">
                  Imagine offers a wide range of features to help you create stunning visuals with ease. From advanced
                  image editing tools to seamless collaboration, Imagine has everything you need to bring your ideas to
                  life.
                </p>
              </div>
            </div>
            <div
              className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-4">
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Intuitive Interface</h3>
                    <p className="text-lg text-white">
                      Imagine's user-friendly interface makes it easy to create and edit your images with just a few
                      clicks.
                    </p>
                  </div>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Advanced Editing</h3>
                    <p className="text-lg text-white">
                      Leverage powerful AI-driven tools to enhance, manipulate, and refine your images with precision.
                    </p>
                  </div>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Seamless Collaboration</h3>
                    <p className="text-lg text-white">
                      Invite your team to collaborate on projects, provide feedback, and iterate on your designs in
                      real-time.
                    </p>
                  </div>
                </div>
              </div>
              <img
                src="https://i.pinimg.com/736x/73/eb/04/73eb04196a11ef1173bd0782104588e5.jpg"
                width={550}
                height={310}
                alt="Features"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last" />
            </div>
          </div>
        </section>
        <section id="testimonials"  ref={testimonialsRef}className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter">What Our Users Say</h2>
                <p
                  className="max-w-[900px] text-lg md:text-xl lg:text-base/relaxed xl:text-xl/relaxed">
                  Hear from our satisfied customers about their experience with Imagine and how it has transformed their
                  creative workflow.
                </p>
              </div>
              <div
                className="grid max-w-5xl grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
                <div
                  className="flex flex-col items-start space-y-4 bg-[#8b00ff] p-6 rounded-lg shadow-lg">
                  <div className="flex items-center gap-2">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <h4 className="text-lg font-bold">John Doe</h4>
                      <p className="text-sm text-muted-foreground">Designer</p>
                    </div>
                  </div>
                  <p className="text-lg">
                    "Imagine has completely transformed my creative workflow.\n The AI-powered tools make it easy to
                    bring my ideas to life\n in a fraction of the time."
                  </p>
                </div>
                <div
                  className="flex flex-col items-start space-y-4 bg-[#8b00ff] p-6 rounded-lg shadow-lg">
                  <div className="flex items-center gap-2">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <h4 className="text-lg font-bold">Jane Smith</h4>
                      <p className="text-sm text-muted-foreground">Illustrator</p>
                    </div>
                  </div>
                  <p className="text-lg">
                    "Imagine has been a game-changer for my creative process.\n The seamless collaboration features make
                    it easy to work\n with my team and get feedback in real-time."
                  </p>
                </div>
                <div
                  className="flex flex-col items-start space-y-4 bg-[#8b00ff] p-6 rounded-lg shadow-lg">
                  <div className="flex items-center gap-2">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <h4 className="text-lg font-bold">Michael Johnson</h4>
                      <p className="text-sm text-muted-foreground">Photographer</p>
                    </div>
                  </div>
                  <p className="text-lg">
                    "Imagine has completely transformed the way I approach my\n photography projects. The advanced
                    editing tools have\n allowed me to take my work to the next level."
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#6a5acd]">
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
              <div className="space-y-4">
                <div className="inline-block rounded-lg bg-[#8b00ff] px-3 py-1 text-sm">Try Imagine</div>
                <h2
                  className="lg:leading-tighter text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter">
                  Unleash Your Creativity Today
                </h2>
               
              </div>
              <div className="flex flex-col items-start space-y-4">
                <div className="inline-block rounded-lg bg-[#8b00ff] px-3 py-1 text-sm">Get Started</div>
                <p className="mx-auto max-w-[700px] text-lg md:text-xl/relaxed">
                  Imagine is the ultimate AI-powered image generation tool that will transform the way you create
                  visuals. Sign up today and start unleashing your creativity.
                </p>
                
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-[#8b00ff]">
        <p className="text-xs text-white">&copy; 2024 Imagine By SIVASISH. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <a
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}>
            Terms of Service
          </a>
          <a
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}>
            Privacy
          </a>
        </nav>
      </footer>
    </div>)
  );
}

function ImageIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
